/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("aptdb.kotlin-library-conventions")
    id("io.arrow-kt.analysis.kotlin") version "2.0.2"
}

dependencies {
    implementation("com.lordcodes.turtle:turtle:0.6.0")
}
