/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("aptdb.kotlin-library-conventions")
}

dependencies {
    implementation("com.lordcodes.turtle:turtle:0.6.0")
}
