/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package aptdb.app

import aptdb.core.apt.*

fun main() {
  val aptConfig = AptConfiguration.create(DefaultConfigurationProvider)
  aptConfig.str().forEach { println(it) }
}
